apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.secrets" . }}
type: Opaque
data:
  awsAccessKeyId: {{ required "A valid aws.accessKeyId entry required!"  .Values.aws.accessKeyId | b64enc }}
  awsSecretAccessKey: {{ required "A valid aws.secretAccessKey entry required!"  .Values.aws.secretAccessKey | b64enc }}
  {{- if .Values.aws.sessionToken }}
  awsSessionToken: {{ .Values.aws.sessionToken | b64enc }}
  {{- end }}
